### ISSUE TITLE
`window is not defined` error when trying to build with Next.js

### ISSUE THREAD

**Issue by timendez** [akashuba/react-timeline-animation#1]
```
> Build error occurred
ReferenceError: window is not defined
    at Object.<anonymous> (node_modules\react-timeline-animation\dist\index.js:48:24)
```

From a fresh install, if I try to build I get that compile error

**Comment by timendez** [comment]
I had to wrap `window` in:
```javascript
if (typeof window !== "undefined") {
  var halfScreenHeight = window.innerHeight / 2;
}
```

**Comment by akashuba** [comment]
Thanks, I will work on it. 
Be free to propose your solution on PR.

UPD: аdd type guards for "window" but keep it open until trying on Next.js.

**Comment by jaycoolslm** [comment]
Hi, I know I am a bit late! But, I've fixed this issue by importing the module dynamically using dynamic from "next/dynamic"

![image](https://user-images.githubusercontent.com/86686746/189544447-59b1ee96-69e2-4d05-9739-97e8efef5885.png)
