### ISSUE TITLE
timeline option to follow in both directions

### ISSUE THREAD

**Issue by dohomi** [akashuba/react-timeline-animation#2]
Hello
I like your simple approach of the timeline animation. Is there a possibility, that the animation of the connector would go in both direction? Currently once the timeline ends on the bottom the animation is and if the user scrolls up nothing changes any longer. It would be great if the animation stays active / maybe as an additional option.
Cheers

**Comment by abhikapoor** [comment]
I am also looking for the same solution . Would be nice if the scrolling is possible both directions

**Comment by abhikapoor** [comment]
@dohomi  did you found any solution yet ?

**Comment by dohomi** [comment]
@abhikapoor not yet

**Comment by akashuba** [comment]
Add hasReverse prop.
